// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBminsa7oMDsWxbGCXJtqnTmdIrEUcQUWU',
    appId: '1:958103491933:web:fbfd42a8dc46d45a4a44b4',
    messagingSenderId: '958103491933',
    projectId: 'shopify-f5fe9',
    authDomain: 'shopify-f5fe9.firebaseapp.com',
    storageBucket: 'shopify-f5fe9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXUcqNVjkjuSFTiwhNFdj_NBMA9ZQrIL0',
    appId: '1:958103491933:android:1ad464555d944fea4a44b4',
    messagingSenderId: '958103491933',
    projectId: 'shopify-f5fe9',
    storageBucket: 'shopify-f5fe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMvixwouSUuc0ROLsOsOBpRImDb4rt2Lw',
    appId: '1:958103491933:ios:30d14c4962a201524a44b4',
    messagingSenderId: '958103491933',
    projectId: 'shopify-f5fe9',
    storageBucket: 'shopify-f5fe9.appspot.com',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMvixwouSUuc0ROLsOsOBpRImDb4rt2Lw',
    appId: '1:958103491933:ios:30d14c4962a201524a44b4',
    messagingSenderId: '958103491933',
    projectId: 'shopify-f5fe9',
    storageBucket: 'shopify-f5fe9.appspot.com',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBminsa7oMDsWxbGCXJtqnTmdIrEUcQUWU',
    appId: '1:958103491933:web:e59b9382af195a3d4a44b4',
    messagingSenderId: '958103491933',
    projectId: 'shopify-f5fe9',
    authDomain: 'shopify-f5fe9.firebaseapp.com',
    storageBucket: 'shopify-f5fe9.appspot.com',
  );
}
